# Generated by Django 5.1 on 2024-10-03 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0002_users_twostepauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('screenshots', models.FileField(upload_to='')),
                ('videos', models.FileField(upload_to='')),
                ('files', models.FileField(upload_to='')),
                ('description', models.TextField(max_length=2000)),
                ('comments', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
            },
        ),
        migrations.DeleteModel(
            name='Startups',
        ),
        migrations.AddIndex(
            model_name='works',
            index=models.Index(fields=['user', 'description'], name='website_app_user_id_dde6db_idx'),
        ),
    ]
