# Generated by Django 5.1 on 2024-10-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0003_works_delete_startups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='reputation',
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='Phone number'),
        ),
    ]
