# Generated by Django 5.1 on 2024-11-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0004_remove_users_reputation_users_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='hiddenprofile',
            field=models.BooleanField(default=False, verbose_name='Hidden profile'),
        ),
    ]
