# Generated by Django 5.1 on 2024-12-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0005_users_hiddenprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='hiddenprofile',
        ),
    ]
