# Generated by Django 5.1 on 2024-12-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0006_remove_users_hiddenprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profession',
            field=models.CharField(default='Unemployed', max_length=50, verbose_name='Profession'),
        ),
    ]
