# Generated by Django 5.1 on 2024-12-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0007_users_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='default_profile.png', upload_to='users_profile_pictures/', verbose_name='Profile picture'),
        ),
    ]
