# Generated by Django 5.1 on 2024-12-25 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0008_users_avatar'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='works',
            name='website_app_user_id_dde6db_idx',
        ),
        migrations.AddField(
            model_name='works',
            name='speciality',
            field=models.CharField(max_length=50, null=True, verbose_name='Speciality'),
        ),
        migrations.AlterField(
            model_name='works',
            name='description',
            field=models.TextField(max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='works',
            name='files',
            field=models.FileField(upload_to='', verbose_name='Files'),
        ),
        migrations.AlterField(
            model_name='works',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Portfolio name'),
        ),
        migrations.AlterField(
            model_name='works',
            name='screenshots',
            field=models.FileField(upload_to='', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='works',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='works',
            name='videos',
            field=models.FileField(upload_to='', verbose_name='Videos'),
        ),
        migrations.AddIndex(
            model_name='works',
            index=models.Index(fields=['user', 'speciality', 'name'], name='website_app_user_id_94239a_idx'),
        ),
    ]
