# Generated by Django 5.1 on 2024-12-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0009_remove_works_website_app_user_id_dde6db_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='screenshots',
            field=models.ImageField(upload_to='', verbose_name='Images'),
        ),
    ]
