# Generated by Django 5.1 on 2025-01-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0013_alter_messages_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='topic',
            field=models.CharField(max_length=30, null=True, verbose_name='Message topic'),
        ),
    ]
